#pragma once
#define _Use_decl_annotations_
#define _Analysis_assume_(x)
#define _In_
#define _In_opt_
#define _In_z_
#define _In_z_count_(i)
#define _In_reads_(i)
#define _In_reads_bytes_(x)
#define _In_reads_opt_(i)
#define _Out_
#define _Out_opt_
#define _Out_writes_(i)
#define _Out_writes_bytes_(i)
#define _Out_writes_opt_(i)
#define _Inout_updates_all_(i)
#define _Inout_updates_all_opt_(i)
#define _Inout_updates_bytes_all_(i)
#define _Inout_
#define _When_(x, y)
#define _Inout_opt_
#define __in_ecount(size)
#define __out_ecount(size)
#define _Success_(x)
